apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-note
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delete-note
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5003"
      labels:
        app: delete-note
    spec:
      containers:
      - name: delete-note
        image: armangupta/delete-note-service:newlatest
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
        resources:
          limits:
            cpu: 300m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 512Mi