apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: add-note-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: add-note
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75  # Scale when CPU usage exceeds 75%
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75  # Scale when Memory usage exceeds 75%