apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-exporter-config
data:
  my.cnf: |
    [client]
    user=root
    password=qwertyuiop
    host=mysql.default.svc.cluster.local
    port=3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104"
    spec:
      containers:
      - name: mysql-exporter
        image: prom/mysqld-exporter:v0.17.2
        args:
        - --config.my-cnf=/etc/mysql-exporter/my.cnf
        - --web.listen-address=:9104
        - --log.level=debug
        ports:
        - containerPort: 9104
        volumeMounts:
        - name: mysql-config
          mountPath: /etc/mysql-exporter
      volumes:
      - name: mysql-config
        configMap:
          name: mysql-exporter-config