apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9104"
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - name: metrics
      port: 9104
      targetPort: 9104
  type: ClusterIP
