apiVersion: v1
kind: Service
metadata:
  name: get-note
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5004"
spec:
  type: ClusterIP
  selector:
    app: get-note
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5004