apiVersion: v1
kind: Service
metadata:
  name: add-note
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5001"
spec:
  selector:
    app: add-note
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP