apiVersion: v1
kind: Service
metadata:
  name: update-note
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5002"
spec:
  type: ClusterIP
  selector:
    app: update-note
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002